spring:
  application:
    name: AIAutoCode
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aicode?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: music123
  session:
    store-type: redis
#    session 30天 过期
    timeout: 259200
  #redis
  data:
    redis:
      host: localhost
      port: 6379
      password:
      ttl: 3600
  profiles:
    active: local

server:
  port: 8080
  servlet:
    context-path: /api
#    cookie30天过期
    session:
      cookie:
        max-age: 259200

logging:
  charset:
    console: UTF-8

springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.czjtu.aiautocode.controller

knife4j:
  enable: true
  setting:
    language: zh_cn