spring:
  application:
    name: AIAutoCode
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aicode?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: music123
  session:
    store-type: redis
#    session 30天 过期
    timeout: 259200
  #redis
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password:
      ttl: 3600
  profiles:
    active: local

server:
  port: 8080
  servlet:
    context-path: /api
#    cookie30天过期
    session:
      cookie:
        max-age: 259200

logging:
  charset:
    console: UTF-8

springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.czjtu.aiautocode.controller

knife4j:
  enable: true
  setting:
    language: zh_cn
# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: <YOUR-API-KEY>
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      max-tokens: 8192
    #      strict-json-schema: true
#      response-format: json_object
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: <YOUR-API-KEY>
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      max-tokens: 8192
    # 推理 AI 模型配置（用于复杂的推理任务）
    reasoning-streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: <YOUR-API-KEY>
      model-name: deepseek-reasoner
      max-tokens: 32768
      temperature: 0.1
      log-requests: true
      log-responses: true
    # 智能路由 AI 模型配置（用于简单的分类任务）
    routing-chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: <YOUR-API-KEY>
      model-name: qwen-turbo
      max-tokens: 100
      log-requests: true
      log-responses: true

# 添加 COS 对象存储配置（需要从腾讯云获取）
cos:
  client:
    host: https://aicode-1382151313.cos.ap-beijing.myqcloud.com
    secretId: <YOUR-API-KEY>
    secretKey: <YOUR-API-KEY>
    region: ap-beijing
    bucket: aicode-1382151313

#pexels
pexels:
  api-key: <YOUR-API-KEY>

# 阿里云 DashScope 配置
dashscope:
  api-key: <YOUR-API-KEY>
  image-model: wan2.2-t2i-flash

